//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/Daniel/IdeaProjects/LanguageSyntax/src/Syntax.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SyntaxParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ISyntaxVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] SyntaxParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>notLastCommand</c>
	/// labeled alternative in <see cref="SyntaxParser.commands"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotLastCommand([NotNull] SyntaxParser.NotLastCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>lastCommand</c>
	/// labeled alternative in <see cref="SyntaxParser.commands"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLastCommand([NotNull] SyntaxParser.LastCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionCommand</c>
	/// labeled alternative in <see cref="SyntaxParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCommand([NotNull] SyntaxParser.FunctionCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>termsCommand</c>
	/// labeled alternative in <see cref="SyntaxParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTermsCommand([NotNull] SyntaxParser.TermsCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>notLastTerm</c>
	/// labeled alternative in <see cref="SyntaxParser.terms"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotLastTerm([NotNull] SyntaxParser.NotLastTermContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>lastTerm</c>
	/// labeled alternative in <see cref="SyntaxParser.terms"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLastTerm([NotNull] SyntaxParser.LastTermContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>controlTerm</c>
	/// labeled alternative in <see cref="SyntaxParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitControlTerm([NotNull] SyntaxParser.ControlTermContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>statementTerm</c>
	/// labeled alternative in <see cref="SyntaxParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatementTerm([NotNull] SyntaxParser.StatementTermContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>commentTerm</c>
	/// labeled alternative in <see cref="SyntaxParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommentTerm([NotNull] SyntaxParser.CommentTermContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>useValue</c>
	/// labeled alternative in <see cref="SyntaxParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUseValue([NotNull] SyntaxParser.UseValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>readValue</c>
	/// labeled alternative in <see cref="SyntaxParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReadValue([NotNull] SyntaxParser.ReadValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>flagValue</c>
	/// labeled alternative in <see cref="SyntaxParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlagValue([NotNull] SyntaxParser.FlagValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>lengthOfValue</c>
	/// labeled alternative in <see cref="SyntaxParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLengthOfValue([NotNull] SyntaxParser.LengthOfValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>listElementValue</c>
	/// labeled alternative in <see cref="SyntaxParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListElementValue([NotNull] SyntaxParser.ListElementValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberValue</c>
	/// labeled alternative in <see cref="SyntaxParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberValue([NotNull] SyntaxParser.NumberValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>textValue</c>
	/// labeled alternative in <see cref="SyntaxParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTextValue([NotNull] SyntaxParser.TextValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>identifierValue</c>
	/// labeled alternative in <see cref="SyntaxParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifierValue([NotNull] SyntaxParser.IdentifierValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.lengthOf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLengthOf([NotNull] SyntaxParser.LengthOfContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] SyntaxParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] SyntaxParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.listElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListElement([NotNull] SyntaxParser.ListElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.nonKeywordName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNonKeywordName([NotNull] SyntaxParser.NonKeywordNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] SyntaxParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.nonZeroNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNonZeroNumber([NotNull] SyntaxParser.NonZeroNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.digit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDigit([NotNull] SyntaxParser.DigitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.nonZeroDigit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNonZeroDigit([NotNull] SyntaxParser.NonZeroDigitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.flag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlag([NotNull] SyntaxParser.FlagContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitText([NotNull] SyntaxParser.TextContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.textWithoutNewlineOrQuotationmarks"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTextWithoutNewlineOrQuotationmarks([NotNull] SyntaxParser.TextWithoutNewlineOrQuotationmarksContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>loopStructure</c>
	/// labeled alternative in <see cref="SyntaxParser.controlStructures"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoopStructure([NotNull] SyntaxParser.LoopStructureContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ifElseStructure</c>
	/// labeled alternative in <see cref="SyntaxParser.controlStructures"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfElseStructure([NotNull] SyntaxParser.IfElseStructureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoop([NotNull] SyntaxParser.LoopContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ifNoElse</c>
	/// labeled alternative in <see cref="SyntaxParser.if_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfNoElse([NotNull] SyntaxParser.IfNoElseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ifWithElse</c>
	/// labeled alternative in <see cref="SyntaxParser.if_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfWithElse([NotNull] SyntaxParser.IfWithElseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionNoTakes</c>
	/// labeled alternative in <see cref="SyntaxParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionNoTakes([NotNull] SyntaxParser.FunctionNoTakesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionWithTakes</c>
	/// labeled alternative in <see cref="SyntaxParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionWithTakes([NotNull] SyntaxParser.FunctionWithTakesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.takesArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTakesArgument([NotNull] SyntaxParser.TakesArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>notLastParameter</c>
	/// labeled alternative in <see cref="SyntaxParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotLastParameter([NotNull] SyntaxParser.NotLastParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>lastParameter</c>
	/// labeled alternative in <see cref="SyntaxParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLastParameter([NotNull] SyntaxParser.LastParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>givesNothing</c>
	/// labeled alternative in <see cref="SyntaxParser.givesArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGivesNothing([NotNull] SyntaxParser.GivesNothingContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>givesType</c>
	/// labeled alternative in <see cref="SyntaxParser.givesArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGivesType([NotNull] SyntaxParser.GivesTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.nothing"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNothing([NotNull] SyntaxParser.NothingContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>createStatement</c>
	/// labeled alternative in <see cref="SyntaxParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreateStatement([NotNull] SyntaxParser.CreateStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>giveStatement</c>
	/// labeled alternative in <see cref="SyntaxParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGiveStatement([NotNull] SyntaxParser.GiveStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>breakStatement</c>
	/// labeled alternative in <see cref="SyntaxParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakStatement([NotNull] SyntaxParser.BreakStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>useStatement</c>
	/// labeled alternative in <see cref="SyntaxParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUseStatement([NotNull] SyntaxParser.UseStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>printStatement</c>
	/// labeled alternative in <see cref="SyntaxParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintStatement([NotNull] SyntaxParser.PrintStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>readStatement</c>
	/// labeled alternative in <see cref="SyntaxParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReadStatement([NotNull] SyntaxParser.ReadStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>assignStatement</c>
	/// labeled alternative in <see cref="SyntaxParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignStatement([NotNull] SyntaxParser.AssignStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] SyntaxParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>createNoInput</c>
	/// labeled alternative in <see cref="SyntaxParser.create"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreateNoInput([NotNull] SyntaxParser.CreateNoInputContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>createWithInput</c>
	/// labeled alternative in <see cref="SyntaxParser.create"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreateWithInput([NotNull] SyntaxParser.CreateWithInputContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>useGive</c>
	/// labeled alternative in <see cref="SyntaxParser.give"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUseGive([NotNull] SyntaxParser.UseGiveContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nothingGive</c>
	/// labeled alternative in <see cref="SyntaxParser.give"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNothingGive([NotNull] SyntaxParser.NothingGiveContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expressionGive</c>
	/// labeled alternative in <see cref="SyntaxParser.give"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionGive([NotNull] SyntaxParser.ExpressionGiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.break"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreak([NotNull] SyntaxParser.BreakContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>useNoInput</c>
	/// labeled alternative in <see cref="SyntaxParser.use"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUseNoInput([NotNull] SyntaxParser.UseNoInputContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>useWithInput</c>
	/// labeled alternative in <see cref="SyntaxParser.use"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUseWithInput([NotNull] SyntaxParser.UseWithInputContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>notLastInput</c>
	/// labeled alternative in <see cref="SyntaxParser.useInput"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotLastInput([NotNull] SyntaxParser.NotLastInputContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>lastInput</c>
	/// labeled alternative in <see cref="SyntaxParser.useInput"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLastInput([NotNull] SyntaxParser.LastInputContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrint([NotNull] SyntaxParser.PrintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.read"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRead([NotNull] SyntaxParser.ReadContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>valueExpression</c>
	/// labeled alternative in <see cref="SyntaxParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueExpression([NotNull] SyntaxParser.ValueExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>infixExpression</c>
	/// labeled alternative in <see cref="SyntaxParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInfixExpression([NotNull] SyntaxParser.InfixExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>convertExpression</c>
	/// labeled alternative in <see cref="SyntaxParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConvertExpression([NotNull] SyntaxParser.ConvertExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parensExpression</c>
	/// labeled alternative in <see cref="SyntaxParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParensExpression([NotNull] SyntaxParser.ParensExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperator([NotNull] SyntaxParser.OperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.character"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharacter([NotNull] SyntaxParser.CharacterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.symbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSymbol([NotNull] SyntaxParser.SymbolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.symbolWithoutNewline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSymbolWithoutNewline([NotNull] SyntaxParser.SymbolWithoutNewlineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.wsc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWsc([NotNull] SyntaxParser.WscContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComment([NotNull] SyntaxParser.CommentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.a"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitA([NotNull] SyntaxParser.AContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.b"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitB([NotNull] SyntaxParser.BContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.c"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitC([NotNull] SyntaxParser.CContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.d"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitD([NotNull] SyntaxParser.DContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.e"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitE([NotNull] SyntaxParser.EContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.f"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitF([NotNull] SyntaxParser.FContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.g"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitG([NotNull] SyntaxParser.GContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.h"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitH([NotNull] SyntaxParser.HContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.i"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitI([NotNull] SyntaxParser.IContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.j"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJ([NotNull] SyntaxParser.JContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.k"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitK([NotNull] SyntaxParser.KContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.l"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitL([NotNull] SyntaxParser.LContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.m"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitM([NotNull] SyntaxParser.MContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.n"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitN([NotNull] SyntaxParser.NContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.o"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitO([NotNull] SyntaxParser.OContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.p"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitP([NotNull] SyntaxParser.PContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.q"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQ([NotNull] SyntaxParser.QContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.r"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR([NotNull] SyntaxParser.RContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.s"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitS([NotNull] SyntaxParser.SContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.t"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitT([NotNull] SyntaxParser.TContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.u"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitU([NotNull] SyntaxParser.UContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.v"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitV([NotNull] SyntaxParser.VContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.w"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitW([NotNull] SyntaxParser.WContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.x"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitX([NotNull] SyntaxParser.XContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.y"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitY([NotNull] SyntaxParser.YContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SyntaxParser.z"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitZ([NotNull] SyntaxParser.ZContext context);
}
